brace_style = "AlwaysNextLine"
comment_width = 100
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
max_width = 100
reorder_modules = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
